export default {
  login: "Doc-Hanzala",
  id: 129552329,
  node_id: "U_kgDOB7jPyQ",
  avatar_url: "https://avatars.githubusercontent.com/u/129552329?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Doc-Hanzala",
  html_url: "https://github.com/Doc-Hanzala",
  followers_url: "https://api.github.com/users/Doc-Hanzala/followers",
  following_url:
    "https://api.github.com/users/Doc-Hanzala/following{/other_user}",
  gists_url: "https://api.github.com/users/Doc-Hanzala/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Doc-Hanzala/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Doc-Hanzala/subscriptions",
  organizations_url: "https://api.github.com/users/Doc-Hanzala/orgs",
  repos_url: "https://api.github.com/users/Doc-Hanzala/repos",
  events_url: "https://api.github.com/users/Doc-Hanzala/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Doc-Hanzala/received_events",
  type: "User",
  site_admin: false,
  name: "Hanzala Tanveer",
  company: null,
  blog: "https://linktr.ee/hanzalatanveer",
  location: "Pakistan",
  email: null,
  hireable: null,
  bio: "React Js Developer",
  twitter_username: null,
  public_repos: 45,
  public_gists: 0,
  followers: 49,
  following: 11,
  created_at: "2023-03-31T20:04:02Z",
  updated_at: "2023-11-13T09:21:35Z",
};